### ISSUE TITLE
page index in acquire_page

### ISSUE THREAD

**Issue by lineagech** [ZaidQureshi/bam#10]
Hi, I think the following code may cause invalid accesses:

include/page_cache.h:1477
```CUDA
coalesce_page(lane, mask, r, page, gaddr, false, eq_mask, master, count, base_master);
page_ = &r_->pages[base_master];
```
the returned base_master could exceed the number of pages in the current range if size of page cache is larger than the size of the range and causes invalid access of r_->pages. Could you help check this is an issue? or I misused the bam_ptr here. Thanks!

**Comment by ZaidQureshi** [comment]
If you look at the how `coalesce_page` gets the `base_master` value, you will notice it gets it from the range itself. 
https://github.com/ZaidQureshi/bam/blob/master/include/page_cache.h#L1355

**Comment by lineagech** [comment]
My experiment settings are:

benchmark/vectoradd/settings.h:
```CUDA
numThreads = 256;
pageSize = 65536;
maxPageCacheSize = 25769803776;
n_elems = 1076277500;
```
Got error: 
```
CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x555555f01b60 (__atomic_generated:1049)
```

This error can be temporarily solved by:
include/page_cache.h: 1488
``` CUDA
coalesce_page(lane, mask, r, page, gaddr, false, eq_mask, master, count, base_master);
//page_ = &r_->pages[base_master];
page_ = &r_->pages[page];
```

**Comment by ZaidQureshi** [comment]
Have you run this under cuda-memcheck to see exactly where the error is coming from?

**Comment by msharmavikram** [comment]
I believe this is no longer an issue based on our discussions. If not, please reopen or submit PR for the fix.
