### ISSUE TITLE
Error when loading the custom kernel module

### ISSUE THREAD

**Issue by Liu-rj** [ZaidQureshi/bam#13]
Hi, I'm attempting to build the project but when I run `sudo make load` to load the custom kernel module, it gives me
> insmod libnvm.ko max_num_ctrls=64
insmod: ERROR: could not insert module libnvm.ko: Unknown symbol in module
make: *** [Makefile:24: load] Error 1

And I check the `dmesg` and it reports:
>[64532.536098] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
[64532.543921] libnvm: Unknown symbol nvidia_p2p_dma_unmap_pages (err -2)
[64532.543950] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
[64532.551627] libnvm: Unknown symbol nvidia_p2p_get_pages (err -2)
[64532.551636] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
[64532.559403] libnvm: Unknown symbol nvidia_p2p_put_pages (err -2)
[64532.559411] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
[64532.567112] libnvm: Unknown symbol nvidia_p2p_dma_map_pages (err -2)
[64532.567119] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
[64532.574778] libnvm: Unknown symbol nvidia_p2p_free_page_table (err -2)

I wonder what is the problem and how to solve it?

I run the build on an aws instance with
* Linux version 5.15.0-1038-aws #43~20.04.1-Ubuntu
* Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
* Nvidia V100 GPU
* Driver version: 525.85.12, CUDA version: 11.8

Thanks

**Comment by msharmavikram** [comment]
BaM codebase never tested on AWS or any cloud environment. We do not know if it works or not and what underlying VM/cloud stack can restrict BaM deployment. 

W. R. T to the error that you are observing, this seems to be issue where Nvidia driver modules are not compiled. Please go to '/usr/src/nvidia-525.xxx/' and run 'sudo make'. Following this, please rebuild BaM from scratch (delete everything in build folder). 

If the problem persists, please check if you using the right driver version with the kernel version.

**Comment by msharmavikram** [comment]
You should not be getting this error if you nvidia driver is compiled. Can you clean up the build directory and retry from scratch so that we take updated files?

**Comment by ShenJunkun** [comment]
> You should not be getting this error if you nvidia driver is compiled. Can you clean up the build directory and retry from scratch so that we take updated files?

I have the same problem.

`dmesg` reports that 

>  libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
> [35521.216277] libnvm: Unknown symbol nvidia_p2p_dma_unmap_pages (err -2)
> [35521.216295] libnvm: module using GPL-only symbols uses symbols from proprietary module nvidia.
> [35521.216297] libnvm: Unknown symbol nvidia_p2p_get_pages (err -2)

[This blog](https://forums.developer.nvidia.com/t/can-t-insert-module-libnvm-ko-unknown-symbol/236332) says that 

> Hi, This issue relate to GPL. If you have A100 support service, please contact the corresponding technical support team for the help. Thanks!

Does this mean a violation of the gpl license? Did you encounter the same problem and how did you solve it?

Many thanks.

**Comment by msharmavikram** [comment]
This implies there is a kernel version and Nvidia driver version mismatch and the system configuration is not correctly set up. Please follow the https://github.com/ZaidQureshi/bam#system-configurations instructions correctly. 

In our setup, we used 5.8.x kernel with Nvidia driver 525.xx in Ubuntu 22.04 LTS - on-prem device. We tested both A100 and V100 (many drivers from 440.xx to 525.xx). We faced no issues. We have not validated our solution in the cloud setup. 

Given in your case of testing - Linux version 5.15.0-1038-aws #43~20.04.1-Ubuntu with 525.85.12 driver for V100, we are not sure if you are running into compatibility issues. `unknown symbol` errors are not due to BaM codebase and are a result of not configuring system correctly.

**Comment by ZaidQureshi** [comment]
This is an issue of the Linux kernel version. Newer kernel versions don't let modules using non-gpl symbols to use gpu symbols.
We have tried on linux kernel 5.8.x, like Vikram said, and that should work.

**Comment by Liu-rj** [comment]
Yes, switch to linux kernel 5.4.0 with Nvidia driver 515.65.01 solves the problem.

Another workaround may be using [open-source Nvidia kernel modules](https://github.com/NVIDIA/open-gpu-kernel-modules), but I haven't tested it.

I may close this issue. Thank you!

**Comment by Baizx98** [comment]
Using open-source Nvidia driver can solve the problem.

**Comment by augierg** [comment]
> Using open-source Nvidia driver can solve the problem.

Unfortunately the V100 is too old for the open driver. See the [Supported GPUs](https://developer.nvidia.com/blog/nvidia-transitions-fully-towards-open-source-gpu-kernel-modules/#supported_gpus) section.
