### ISSUE TITLE
where to get the dataset ?

### ISSUE THREAD

**Issue by LiangZhou9527** [ZaidQureshi/bam#14]
Hi guys, 

I'm new to BaM and currently I can run the array benchmark on my machine successfully.
So I'm going to run the BFS benchmark but I'm wondering how to get the dataset (graph raw dataset) firstly ?

Appreciated if anyone could share the dataset to me :-)

Thanks.

**Comment by msharmavikram** [comment]
Hi @LiangZhou9527 ,

We still haven't figured out what to do for sharing the datasets. There are two key problems:

1. Licensing - which we do not have full control. 
2. Size - cost of hosting the dataset over time and payment for each egress requests. 

Both of these are not easy to solve sustainably. 

Our current recommended approach which most people who are using BaM have taken is to follow the dataset generation principle laid out in our EMOGI GitHub repo (https://github.com/illinois-impact/EMOGI#dataset) 

Let us know if that works for you. If not, we will have to spend time on figuring the 1 and 2 out.
