### ISSUE TITLE
nvm-block-bench causes Segmentation fault

### ISSUE THREAD

**Issue by Liu-rj** [ZaidQureshi/bam#15]
Hi, I'm able to sucessfully build the project but when I run the block benchmark as instructed:

```
sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024  --page_size=512 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=128 --random=true
```

However, it simply gives me `Segmentation fault` without any additional information. I'm not aware of where the problem is.

I build the project on an AWS instance with
* Linux version 5.4.0-1089-aws #97~18.04.1-Ubuntu
* Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
* Nvidia V100 GPU
* Driver version: 515.65.01, CUDA version: 11.7

Thanks

**Comment by msharmavikram** [comment]
As we mentioned in our previous comment, BaM is not tested in cloud instance and we are not sure of types of issues that can pop up. Enabling BaM likely will require substantial effort depending on how cloud stack is created. 

W. R. T the segmentation fault - this error occurs when a CPU thread tries to access an unallocated or non permissible memory location. I recommend adding prints (anything) to determine which specific line in the codebase the segmentation fault is happening. Please let us know what specific line caused it. 

Please note, BaM codebase is well tested across several on-prem devices (nothing on cloud setup). Given this, we will mark this not as bug unless we determine the issue can be reproducable in the on-prem system.
