### ISSUE TITLE
A question about hardware requirements

### ISSUE THREAD

**Issue by 785336111** [ZaidQureshi/bam#16]
Hi, can I use a V100 graphics card with NVlink interface for BaM?

**Comment by msharmavikram** [comment]
This question is unclear. We had previously tested V100 GPU. What is unclear is what do you want to do with nvlink here?

**Comment by 785336111** [comment]
sry，I want to know that can we use GPU V100 SXM2 for NVlink, instead of V100 for PCIe, to build the BaM system? According to the system requirements, a x86 system supporting PCIe P2P is needed. Our server ：
CPU : Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
GPU:  V100 SXM2 (32G) for NVlink * 8

**Comment by 785336111** [comment]
Thanks for your reply, I'll have a try
