### ISSUE TITLE
Is it necessary to install GPU Direct Storage or GPU Direct RDMA before installing Bam?

### ISSUE THREAD

**Issue by zhanglizhi15** [ZaidQureshi/bam#20]
I encountered some issues while installing Bam. I would like to know if GPU Direct Storage needs to be installed before installing Bam?

**Comment by msharmavikram** [comment]
No. Please follow the instructions as discussed in https://github.com/ZaidQureshi/bam#hardwaresystem-requirements section and the next. If you are running in cloud, we cannot say if it will work or not.

**Comment by zhanglizhi15** [comment]
Okay, thank you for your feedback.

**Comment by msharmavikram** [comment]
Please reopen if you have issues.
