### ISSUE TITLE
Error when making benchmarks

### ISSUE THREAD

**Issue by zhanglizhi15** [ZaidQureshi/bam#21]
Hi, I'm attempting to build the project but when I run `sudo make benchmarks ` to load the custom kernel module, it gives me

> ptxas /tmp/tmpxft_00001971_00000000-8_main.compute_70.ptx, line 10944; error   : Unknown modifier '.mmio'
> ptxas /tmp/tmpxft_00001971_00000000-8_main.compute_70.ptx, line 11276; error   : Unknown modifier '.mmio'
> ptxas /tmp/tmpxft_00001971_00000000-8_main.compute_70.ptx, line 11608; error   : Unknown modifier '.mmio'
> ptxas fatal   : Ptx assembly aborted due to errors
> CMake Error at iodepth-block-benchmark-module_generated_main.cu.o.cmake:279 (message):
>   Error generating file
>   /nvme/bam/build/benchmarks/iodepth-block/CMakeFiles/iodepth-block-benchmark-module.dir//./iodepth-block-benchmark-module_generated_main.cu.o

I wonder what is the problem and how to solve it?

I run the build on a node with

**Machine Setup (please complete the following information):**
 - Linux gn15 5.4.0-47-generic #51~18.04.1-Ubuntu
 - Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
 - NVIDIA A100 GPU
 - Diver version:  nvidia-515.65.01, CUDA version: 12.1
 - NVMe SSD

Thanks!

**Comment by msharmavikram** [comment]
Please upgrade the cuda version from 12.1 to 12.2 or newer. Let me know if this fixed your issue.

**Comment by zhanglizhi15** [comment]
Yes, it works when changing the CUDA version to 12.2.  Thanks!
