### ISSUE TITLE
How to get the file offset

### ISSUE THREAD

**Issue by zhanglizhi15** [ZaidQureshi/bam#24]
When processing files on SSD in Bam, GPU needs to obtain the` File Offset `of the file on SSD. The ` File Offset ` may not be the same on each disk. How can I obtain the ` File Offset `?

**Comment by msharmavikram** [comment]
BaM uses physical addressing to access data on the SSD. This implies that when you write the data on the disk, you are responsible for determining where to place the data. This physical address location would be your file offset. 

There are two ways to write the data that BaM supports.
1. You can do replication - then the physical address is constant across SSDs. 
2. You can do striping (RAID-like) - then the physical address required to be calculated on where you have placed it accurately using the striping factor and size of the data you are writing.

**Comment by zhanglizhi15** [comment]
Okay, thank you! If it's just different files on a single SSD, how do I get the `offset` of each file? Is there any tools that can obtain this `offset` value?
I have tried many `Linux` and `NVMe` commands to obtain file addresses, but none of them are quite accurate.

**Comment by msharmavikram** [comment]
BaM requires nvme driver to be in the userspace. So none of the Linux or NVMe commands should work. Remember BaM uses NVMe as memory and NOT AS FILES. So you are in control of where you will be writing the data in the SSD.

**Comment by zhanglizhi15** [comment]
Thanks! Using `nvm-readwrite-bench` allows direct writing of data to the specified location on the SSD. In addition, when writing data, it is important to avoid writing to the `file header section` to avoid any inconvenience during reading.
