### ISSUE TITLE
Utility to Track IO Statistics (IOPS, Throughput, Latency, Utilization, etc.)

### ISSUE THREAD

**Issue by anrahman4** [ZaidQureshi/bam#25]
**Is your feature request related to a problem? Please describe.**

Unable to view NVMe disk level metrics for throughput, IOPS, latency, and other metrics when running benchmark tests.

**Describe the solution you'd like**

I was able to successfully compile and run the initial benchmark tests with nvm-block-bench. With nvidia-smi, I can see the memory utilization and gpu utilization when running the benchmark.

However, I want to be able to see the NVMe disk metrics as I am doing the runs. Something similar to iostat, or what other SPDK libraries offer that essentially replicate what iostat provides. Or, if there is a way to extract this information from /sys/ then I would like to know what directory the files are in so I can do the calculations on my own.

**Describe alternatives you've considered**

No alternatives, I do not see any tool like an iostat for spdk to reveal these metrics. Normally when the device is attached to the normal block level driver, you can access this data through tools like iostat.

**Additional context**
N/A

**Comment by msharmavikram** [comment]
Dear @anrahman4 generating these statistics is nearly impossible without overheads. When we have the overheads, the stats would not be that helpful. Having said that, there is minimal stats support (with overheads) already in the codebase but not documented. You can try calling `print_reset_stats()` function in your host code to generate this data. Check this example: https://github.com/ZaidQureshi/bam/blob/2edd33ce098201d9c375f3fcb1c6e8f64e81b452/benchmarks/vectoradd/main.cu#L538C28-L538C45 

We won't be adding spdk-like stat or iostat capabilities That is good for CPUs and not useful for GPUs and nearly impossible to create.

**Comment by anrahman4** [comment]
Understood. It would have been nice to know, to ensure that the lower level storage is being utilized properly, but I understand. 

For now with nvm-block-bench, I can more or less see the maximum throughput saturation from the bandwidth as well as the operations per second.
