### ISSUE TITLE
[ioctl_map] Page mapping kernel request failed: Invalid argument

### ISSUE THREAD

**Issue by greenchran** [ZaidQureshi/bam#26]
Describe the bug
Hi ! I'm attempting to run the examples but when I run ./bin/nvm-array-bench it gives me:

> SQs: 64	CQs: 64	n_qps: 1
[ioctl_map] Page mapping kernel request failed (ptr=0x7fcf34210000, n_pages=1): Invalid argument
Unexpected error: Failed to map device memory: Invalid argument
Machine Setup (please complete the following information):

**Machine Setup**
- OS: ubuntu 22.04, linux-5.10.213
- Driver Version: 535.161.07, CUDA Version: 12.2
- GPU: Geforce RTX 3060 
- SSD: PC SN730 NVMe SSD

I wonder what is the problem and how to solve it ?
Thanks!

**Comment by msharmavikram** [comment]
Please follow the minimum requirement discussed in https://github.com/ZaidQureshi/bam?tab=readme-ov-file#hardwaresystem-requirements correctly.
