### ISSUE TITLE
Kioxia drives observe freezing of nvm-block-bench when running with n_ctrls greater than or equal to two

### ISSUE THREAD

**Issue by anrahman4** [ZaidQureshi/bam#27]
**Describe the bug**
I am trying to run nvm-block-bench on a Dell PowerEdge XE8545 that has 4x A100 GPUs in them and 2x NVMe SSDs. It works fine when I only use n_ctrls=1 while using gpu0, but anymore than that and the program freezes indefinitely. I have attached parts of dmesg output which shows the following potential errors:

[52272.105362] NVRM: Xid (PCI:0000:41:00): 119, pid=12600, name=nvm-block-bench, Timeout waiting for RPC from GSP1! Expected function 76 (GSP_RM_CONTROL) (0x20803019 0x40).

[52272.105380] CPU: 80 PID: 12600 Comm: nvm-block-bench Tainted: P           OE     5.8.0-63-generic #71~20.04.1-Ubuntu

[52272.105909] WARNING: kernel stack frame pointer at 000000008f1c4968 in nvm-block-bench:12600 has bad value 00000000c9cd6af6

**To Reproduce**
Run the following command:
sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --num_queues=128 --random=true -S 1 --n_ctrls=2

**Expected behavior**
Expected nvm-block-bench to not freeze with n_ctrl >= 2. 

**Machine Setup (please complete the following information):**
 - OS: Ubuntu 20.04.6, Kernel 5.8.0-63-generic
 - NVIDIA Driver: 535.54.03, CUDA Versions: 12.2, GPU name: NVIDIA A100-SXM4-80GB
 - SSD used: KIOXIA CM7

**Additional context**
I have disabled the other 3 GPUs with the following commands as it seems like systems with 4 GPUs or more tends to make nvidia-smi tool freeze or take a long time. However, when other GPUs are disabled, nvidia-smi becomes snappy and responsive.

nvidia-smi -i <pcie_address_gpu> -pm 0
nvidia-smi drain -p <pcie_address_gpu> -m 1

[dmesg.txt](https://github.com/ZaidQureshi/bam/files/14788812/dmesg.txt)
[nvidia-smi.txt](https://github.com/ZaidQureshi/bam/files/14788838/nvidia-smi.txt)

**Comment by msharmavikram** [comment]
Hmm. interesting. 

This should not happen technically. But with Kioxia SSDs, when I tested - sometimes some of their SSDs do not work and some do. I did not bother to figure out what was going wrong. So this may be a weird ask, do you have any other vendor SSD apart from Kioxia CM7? Say, Samsung/Micron? If yes, can you replace them and try them out? (you can do a mix match. so technically you need one SSD). 

Let me know if that works first. If not, we need to determine more in detail and might have to take the discussion offline to an email thread.

**Comment by anrahman4** [comment]
I have to get the system to work with the KIOXIA drives. I may be able to try to plug in different drives later, but right now I cannot try different drives.

I was able to get four KIOXIA drives installed while trying on the other A100 GPUs, n_ctrls = 3 and n_ctrls = 4 result in the same hanging nature at that step.

Is there any kind of logging I can have access to to see why it is hanging? Or we can talk more through email, please let me know where to send the starting email for this. Thank you very much!

**Comment by anrahman4** [comment]
I was actually able to get 2 Micron 7450 Pro drives slotted into the system. I added some print statements to the main.cu file for the block before compiling to see what function it was stuck on. When I ran the test with both n_ctrls=1 and 2 with only the Micron drives bound to the driver, I was able to run the block benchmark as seen below:

sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --num_queues=128 --random=true -S 1 --n_ctrls=1
SQs: 256        CQs: 256        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f3580010000       ee5b0000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:01:00.0
atlaunch kernel
before cuda_err_chk
after cuda_err_chk
before elapsed assignment
Elapsed Time: 229136    Number of Ops: 262144   Data Size (bytes): 1073741824
Ops/sec: 1.14405e+06    Effective Bandwidth(GB/S): 4.36422

sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --num_queues=128 --random=true -S 1 --n_ctrls=2
SQs: 256        CQs: 256        n_qps: 128
SQs: 256        CQs: 256        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f4782010000       fbda0000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:01:00.0
atlaunch kernel
before cuda_err_chk
after cuda_err_chk
before elapsed assignment
Elapsed Time: 116726    Number of Ops: 262144   Data Size (bytes): 1073741824
Ops/sec: 2.2458e+06     Effective Bandwidth(GB/S): 8.56705

Then, I added 1 KIOXIA drive such that there were 3 libnvm devices. Ran the following command for n_ctrls=3:
sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --num_queues=128 --random=true -S 1 --n_ctrls=3
SQs: 128        CQs: 128        n_qps: 128
SQs: 256        CQs: 256        n_qps: 128
SQs: 256        CQs: 256        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7fb2a6010000       fc060000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:01:00.0
atlaunch kernel
before cuda_err_chk

So interestingly enough, although in the commands I specified 128 queues, the Micron drives still report 256 submission and completion queues, while KIOXIA reports at 128 as I would expect. In addition to that, it seems like the code gets stuck at the function called cuda_err_chk. 

Need to do further digging on what cuda_err_chk is doing and why it hangs up on KIOXIA drives when n_ctrls >= 2

**Comment by msharmavikram** [comment]
It looks like the problem is specific to KIOXIA drives. Which system is this? Can you reach out to me over email or LinkedIn? This requires discussion offline.

**Comment by anrahman4** [comment]
I have sent you an email to the email that you have associated with your GitHub account, look forward to discussing with you soon.

**Comment by msharmavikram** [comment]
Continuing discussion over email.

**Comment by cxz66666** [comment]
Any update on this question? We also meet this question!
Here is our setup:
- **SSD**: 12 * Intel P5510
- **OS**: ubuntu22.04, kernel 5.15.0.100
- **CUDA**: 12.3, nvidia-545.23.06(open source)

**Comment by anrahman4** [comment]
@cxz66666 

Issue has been resolved on my end, was able to get max throughput and IOPS off of the 4 drives I was testing on.

I don't know your test system, but some things to consider:

1.) Make sure IOMMU is disabled both in BIOS and in the Linux kernel parameters (iommu=off amd_iommu=off) or (iommu=off intel_iommu=off) depending on what CPU you have.

2.) Run the following command for overall system snappiness with multiple GPUs in system:
sudo /usr/bin/nvidia-persistenced --verbose

3.) With your kernel version, you MUST install the NVIDIA display drivers with the open source version, not the proprietary driver. This will be an option for you if you use a .run file to install both compatible CUDA and NVIDIA display driver at the same time. 

Closing the issue because it is resolved on my end.
