### ISSUE TITLE
Does this project support the Nvidia GPU 3090? 

### ISSUE THREAD

**Issue by TSWorld1314** [ZaidQureshi/bam#29]
I am really interested in this project, but I want to know if this project supports the Nvidia GPU 3090, because I only have this GPU device.

**Comment by TSWorld1314** [comment]
> Really wish this was the case but it's not possible due to limited bar space exposure. So we cannot support it. You may be able to bring up the functionally and might require changes to the stack but won't get the performance.

Okey thanks, I am really interested~ But I have not hardware to support! Could you please give me some suggestions to learn it, I also read this project paper!

**Comment by msharmavikram** [comment]
No idea how to help here especially without the hardware support. The GPU that is need here is any Tesla grade that has GPUDirect support and has reasonable bar space (igb)

**Comment by TSWorld1314** [comment]
Okey, thanks!
