### ISSUE TITLE
What does `ctrl.ctrl->page_size * uints_per_page` mean?

### ISSUE THREAD

**Issue by WWWzq-01** [ZaidQureshi/bam#30]
Hi, I'm looking at this line of code from (https://github.com/ZaidQureshi/bam/blob/d20ef4ac5d4513a411422e41caf48562977504dc/include/page_cache.h#L775) and I'm trying to understand the meaning of ctrl.ctrl->page_size * uints_per_page in the following snippet:
```c++
        const uint32_t uints_per_page = ctrl.ctrl->page_size / sizeof(uint64_t);
        if ((pdt.page_size > (ctrl.ctrl->page_size * uints_per_page)) || (np == 0) || (pdt.page_size < ctrl.ns.lba_data_size))
            throw error(string("page_cache_t: Can't have such page size or number of pages"));
```
Could you please explain what this expression`(ctrl.ctrl->page_size * uints_per_page)` calculates ?Thank you!

**Comment by msharmavikram** [comment]
page_size --> is the cacheline size or IO transfer size.  units per page - basically states how many elements are there. This assertion is trying to determine if the user is correctly using the cacheline definitions. If they are not using it correctly, it will fail.
