### ISSUE TITLE
Correct Memory Allocation for temp1 in page_cache.h

### ISSUE THREAD

**Issue by WWWzq-01** [ZaidQureshi/bam#31]
I noticed the code in include/page_cache.h:
https://github.com/ZaidQureshi/bam/blob/d20ef4ac5d4513a411422e41caf48562977504dc/include/page_cache.h#L810
Wondering if it should be:
```c++
uint64_t* temp1 = new uint64_t[np];
```
or 
```c++
uint64_t* temp1 = (uint64_t*) malloc(np * sizeof(uint64_t));
```

**Comment by msharmavikram** [comment]
What is the issue here? What are you trying to do vs why is this important?

**Comment by WWWzq-01** [comment]
I have a question about the length of this array. Why is it np * sizeof(uint64_t)?
I'm just reading the BaM source code and trying to understand how the page cache is implemented.

**Comment by msharmavikram** [comment]
Please read NVMe specification to understand why this has to be what this has to be :) 

np --> tells you how many pages are there and this part of the routine is for generating PRP list ahead of time.
