### ISSUE TITLE
What is the function of range_t？

### ISSUE THREAD

**Issue by Baizx98** [ZaidQureshi/bam#36]
What is the relationship between array_t and range_t and data_page_t?What is the function of range_t？

**Comment by msharmavikram** [comment]
A simple way to describe - not the most accurate. 

array_t --> provides array abstraction and enables allocation. 
range_t --> maps data to the cache (https://github.com/ZaidQureshi/bam/blob/master/include/page_cache.h#L985)
data_page_t --> is atomic unit abstraction (https://github.com/ZaidQureshi/bam/blob/d20ef4ac5d4513a411422e41caf48562977504dc/include/page_cache.h#L102) for managing states. 

This two theses will provide more details on the intuition of the design. 
Chapter 6 in https://www.ideals.illinois.edu/items/125319 
Chapter 5.3.2 in https://www.ideals.illinois.edu/items/125335

**Comment by msharmavikram** [comment]
Let me know if you have more questions. I am closing the ticket as of now.
