### ISSUE TITLE
The BaM bandwidth is inconsistent with the actual bandwidth provided by the SSD

### ISSUE THREAD

**Issue by LLJING-ER** [ZaidQureshi/bam#49]
Hello,

I'm doing nvm_block_bench benchmark testing on my machine.  
**environment**
NVMe storage: Samsung SSD(PCIe 4.0)*6
Server: QuantaGrid D54Q-2U(PCIe5.0)
**test command**
_./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024  --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=64 --random=true  --access_type=0_

1. The bandwidth of single NVMe storage is around 5 GBps, and expanding to 3 SSD can be up to 15GBps, theoretically increasing to 4 SSD, bandwidth can reach 20GBps, but increasing to 4 SSD bandwidth is 18GBps and 6 SSDs go up to 20GB instead of 25GB. （I'm plugging in 6 SSDs in 1 numa node）
2. Does the _Effective Bandwidth(GB/S)_ in the test result represent the transfer bandwidth between the GPU and the SSD? the 4k random read results are in line with the SSD performance of the fio test, but its 4K random write _(--access_type=1)_ is far higher than the actual performance of the SSD.
FIO 4K random write bandwidth: 1.18GB
nvm_block_bench effectivate Bandwidth: 5GB
However nvm_block_bench is similar to FIO？

Any thoughts about what happens here? Looking forward to hearing from you.

**Comment by gaowayne** [comment]
> Hello,
> 
> I'm doing nvm_block_bench benchmark testing on my machine. **environment** NVMe storage: Samsung SSD(PCIe 4.0)*6 Server: QuantaGrid D54Q-2U(PCIe5.0) **test command** _./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=64 --random=true --access_type=0_
> 
> 1. The bandwidth of single NVMe storage is around 5 GBps, and expanding to 3 SSD can be up to 15GBps, theoretically increasing to 4 SSD, bandwidth can reach 20GBps, but increasing to 4 SSD bandwidth is 18GBps and 6 SSDs go up to 20GB instead of 25GB. （I'm plugging in 6 SSDs in 1 numa node）
> 2. Does the _Effective Bandwidth(GB/S)_ in the test result represent the transfer bandwidth between the GPU and the SSD? the 4k random read results are in line with the SSD performance of the fio test, but its 4K random write _(--access_type=1)_ is far higher than the actual performance of the SSD.
>    FIO 4K random write bandwidth: 1.18GB
>    nvm_block_bench effectivate Bandwidth: 5GB
>    However nvm_block_bench is similar to FIO？
> 
> Any thoughts about what happens here? Looking forward to hearing from you.

did you run precondition before write? BaM have one small cache with GPU memeory.

**Comment by LLJING-ER** [comment]
how to precondition before write?

**Comment by LLJING-ER** [comment]
> > Hello,
> > I'm doing nvm_block_bench benchmark testing on my machine. **environment** NVMe storage: Samsung SSD(PCIe 4.0)*6 Server: QuantaGrid D54Q-2U(PCIe5.0) **test command** _./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=1 --pages=262144 --queue_depth=1024 --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=64 --random=true --access_type=0_
> > 
> > 1. The bandwidth of single NVMe storage is around 5 GBps, and expanding to 3 SSD can be up to 15GBps, theoretically increasing to 4 SSD, bandwidth can reach 20GBps, but increasing to 4 SSD bandwidth is 18GBps and 6 SSDs go up to 20GB instead of 25GB. （I'm plugging in 6 SSDs in 1 numa node）
> > 2. Does the _Effective Bandwidth(GB/S)_ in the test result represent the transfer bandwidth between the GPU and the SSD? the 4k random read results are in line with the SSD performance of the fio test, but its 4K random write _(--access_type=1)_ is far higher than the actual performance of the SSD.
> >    FIO 4K random write bandwidth: 1.18GB
> >    nvm_block_bench effectivate Bandwidth: 5GB
> >    However nvm_block_bench is similar to FIO？
> > 
> > Any thoughts about what happens here? Looking forward to hearing from you.
> 
> did you run precondition before write? BaM have one small cache with GPU memeory.

how to precondition before write?

**Comment by msharmavikram** [comment]
Which gpu?

please note, max bandwidth achievable in gen4 is ~23-24GBps. 

Also when you increase the number of ssds, you need to ensure you submit sufficient IOs to storage. So I would do 1M or 2M requests instead of 256K. Lastly ensure ssds are maxed out on the queues. Don’t cap it.

**Comment by LLJING-ER** [comment]
> Which gpu?
> 
> please note, max bandwidth achievable in gen4 is ~23-24GBps.
> 
> Also when you increase the number of ssds, you need to ensure you submit sufficient IOs to storage. So I would do 1M or 2M requests instead of 256K. Lastly ensure ssds are maxed out on the queues. Don’t cap it.
you means increase _--reqs=1_ and  _--threads=262144_?

**Comment by LLJING-ER** [comment]
I have changed reqs, but bandwidth is also **20GB**, can not up to 23-24GB.
Here's my test log，please check.

(base)/home/bam/build# ./bin/nvm-block-bench --threads=1048576 --blk_size=64 --reqs=1 --pages=1048576 --queue_depth=1024  --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=6 --num_queues=127 --random=true --access_type=0
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7fe878010000       d00bec10000
HEREN
Cond1
100000 8 1 100000
Finish Making Page Cache
finished creating cache
0000:A8:00.0
atlaunch kernel
Elapsed Time: 193370    Number of Ops: 1048576  Data Size (bytes): 4294967296
Ops/sec: 5.42264e+06    Effective Bandwidth(GB/S): 20.6857
(base) /home/bam/build# ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=40 --pages=262144 --queue_depth=1024  --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=6 --num_queues=127 --random=true --access_type=0
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7fc9c0010000       d00bec10000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:A8:00.0
atlaunch kernel
Elapsed Time: 1.93046e+06       Number of Ops: 10485760 Data Size (bytes): 42949672960
Ops/sec: 5.43173e+06    Effective Bandwidth(GB/S): 20.7204
(base) root:/home/bam/build# ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=80 --pages=262144 --queue_depth=1024  --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=6 --num_queues=127 --random=true --access_type=0
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
SQs: 127        CQs: 127        n_qps: 127
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f5f02010000       d00bec10000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:A8:00.0
atlaunch kernel
Elapsed Time: 3.85941e+06       Number of Ops: 20971520 Data Size (bytes): 85899345920
Ops/sec: 5.43386e+06    Effective Bandwidth(GB/S): 20.7285

**Comment by msharmavikram** [comment]
What’s the affinity between gpu and ssd? Are there in the same PCIe tree or do we have a root port or cpu coming in between. 

One more thing to do, can you run 512B page size, from 1 ssd to 6 and send all get logs. It looks like there is bandwidth limit in your system.

**Comment by LLJING-ER** [comment]
Hi, @msharmavikram 
I'll try 512B later, but now I'm more focused on the second question, do you have any suggestions for that?
The questions are shown below，please check.

Does the _Effective Bandwidth(GB/S)_ in the test result represent the transfer bandwidth between the GPU and the SSD? 
the 4k random read results are in line with the SSD performance of the fio test, but its 4K random write (--access_type=1) is far higher than the actual performance of the SSD.
FIO 4K random write bandwidth: 1.18GB
nvm_block_bench effectivate Bandwidth: 5GB
However nvm_block_bench is similar to FIO？

**Comment by msharmavikram** [comment]
How many SSD in this picture? If one, ensure you have warmed up the ssd. To do warm up, do dd and write entire ssd twice. Otherwise what happens is that it always writes to ssd dram.

**Comment by msharmavikram** [comment]
Effective bandwidth is not transfer bandwidth technically. It is lower than the true transfer bandwidth.  We do some “magic” to ensure data is written correctly to the ssd and also reduce the number of doorbell rings. 

Having said that you can ignore these nuances and for all practical purposes you can technically assume it’s same. 

Nvmblockbench is representative of fio and we don’t claim it is equivalent. Hope that is clear.

**Comment by LLJING-ER** [comment]
so _--access_type=1_ it does not mean that it is actually written to the SSD, is my understanding correct？
thanks, I'll redo the warm up and test again.

**Comment by msharmavikram** [comment]
It writes to ssd. However ssd can just write it to ssd dram and slowly write it to nand flash in the background.

**Comment by Tarun-Sreepada** [comment]
Hello.
I am facing a similar problem with random write accesses. 
My SSD supports maximum of 180K IOPS at 4KB (checked with FIO), but when I run the block benchmark at 4KB, it yields 360K IOPS. The benchmark ran for around a minute so I expect the SSD caching behavior effects to be negated.

With 512B page size/the physical page size of the SSD, I get 180K IOPS which matches my SSD spec.

Within the block/main.cu in the write_data or read_data, is the program checking whether all blocks have been read/written or does it return as soon as the initial block has been operated upon?

**Comment by LLJING-ER** [comment]
> Hello. I am facing a similar problem with random write accesses. My SSD supports maximum of 180K IOPS at 4KB (checked with FIO), but when I run the block benchmark at 4KB, it yields 360K IOPS. The benchmark ran for around a minute so I expect the SSD caching behavior effects to be negated.
> 
> With 512B page size/the physical page size of the SSD, I get 180K IOPS which matches my SSD spec. At 1024, 2048 page sizes the IOPS falls within the SSD spec but it is at 4096 where the IOPS spikes 2x higher than it is capable.
> 
> Within the block/main.cu in the write_data or read_data, is the program checking whether all blocks have been read/written or does it return as soon as the initial block has been operated upon?

After doing the precondition , it is back to normal, and you can try to do 4K precondition on the SSD

**Comment by Tarun-Sreepada** [comment]
> > Hello. I am facing a similar problem with random write accesses. My SSD supports maximum of 180K IOPS at 4KB (checked with FIO), but when I run the block benchmark at 4KB, it yields 360K IOPS. The benchmark ran for around a minute so I expect the SSD caching behavior effects to be negated.
> > With 512B page size/the physical page size of the SSD, I get 180K IOPS which matches my SSD spec. At 1024, 2048 page sizes the IOPS falls within the SSD spec but it is at 4096 where the IOPS spikes 2x higher than it is capable.
> > Within the block/main.cu in the write_data or read_data, is the program checking whether all blocks have been read/written or does it return as soon as the initial block has been operated upon?
> 
> After doing the precondition , it is back to normal, and you can try to do 4K precondition on the SSD

I understand. What are the steps for executing precondition? 
Do I unload the libnvm driver, dd into drive with 0 twice, reload the driver and run benchmark?
Or do I just do sequential write to warm up and then run the benchmark?

**Comment by LLJING-ER** [comment]
> > > Hello. I am facing a similar problem with random write accesses. My SSD supports maximum of 180K IOPS at 4KB (checked with FIO), but when I run the block benchmark at 4KB, it yields 360K IOPS. The benchmark ran for around a minute so I expect the SSD caching behavior effects to be negated.
> > > With 512B page size/the physical page size of the SSD, I get 180K IOPS which matches my SSD spec. At 1024, 2048 page sizes the IOPS falls within the SSD spec but it is at 4096 where the IOPS spikes 2x higher than it is capable.
> > > Within the block/main.cu in the write_data or read_data, is the program checking whether all blocks have been read/written or does it return as soon as the initial block has been operated upon?
> > 
> > 
> > After doing the precondition , it is back to normal, and you can try to do 4K precondition on the SSD
> 
> I understand. What are the steps for executing precondition? Do I unload the libnvm driver, dd into drive with 0 twice, reload the driver and run benchmark? Or do I just do sequential write to warm up and then run the benchmark?

I did 2 times sequential write and 1 random write by fio, then reload the libnvm driver and run the test

**Comment by Tarun-Sreepada** [comment]
Thank you. Just to confirm, is this the process I should follow?

```
#unload the driver and get nvme back on
make unload
echo -n "0000:06:00.0" | sudo tee /sys/bus/pci/drivers/nvme/bind

# preconditioning.  2x
sudo dd if=/dev/urandom of=/dev/nvme2n1 bs=1G oflag=direct status=progress

# load driver
sudo sh -c 'echo "0000:06:00.0" > /sys/bus/pci/devices/0000:06:00.0/driver/unbind'
make load

# run nvm-block-bench
```

**Comment by msharmavikram** [comment]
Unload, rebind Linux nvme driver, do dd twice, unbind, load bam driver.
