### ISSUE TITLE
DIRTY flag in bam_ptr?

### ISSUE THREAD

**Issue by lineagech** [ZaidQureshi/bam#8]
Hi, I found no DIRTY flag is set in the following code: 

include/page_cache.h: 477
```CUDA
T& operator[](const size_t i) {
    if ((i < start) || (i >= end)) {
        update_page(i);
    }
    return addr[i-start];
}
```
from benchmark/vectoradd/main.cu: 176

```CUDA
for (size_t j = 0; j < n_elems_per_page; j += WARP_SIZE) {
    idx = start_idx + j; 
    if(idx < n_elems){
        val  = Aptr[idx] + Bptr[idx];
        Cptr[idx] = val; 
```
The code should be changed or do I miss something here? Thanks. 

```CUDA
update_page(i);
page->state.fetch_or(DIRTY, simt::memory_order_relaxed);
```

**Comment by ZaidQureshi** [comment]
Yeah you are correct, we must not have merged that fix in from one of our test branches.
Your fix is exactly correct.
Can you create a PR for this? thanks
